{{ $minioValues := .Values.minio }}
{{ $objStoreConfig := .Values.config.object_storage }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovpn-portal.fullname" . }}
  labels:
    {{- include "ovpn-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  app.yml: |-
    org_name: {{ .Values.config.org_name | quote }}
    session_key: {{ .Values.config.session_key | default (randAlphaNum 32 | b64enc) | quote }}
    default_vpn: {{ .Values.config.default_vpn | quote }}

    object_storage:
      {{- if $minioValues.enabled }}
      {{- $bucket := index $minioValues.buckets 0 }}
      endpoint: http://{{ include "ovpn-portal.minio.fullname" . }}:{{ $minioValues.service.port }}
      access_key: {{ $minioValues.rootUser }}
      secret_key: {{ $minioValues.rootPassword | quote }}
      bucket: {{ $bucket.name }}
      {{- else }}
      endpoint: {{ $objStoreConfig.endpoint }}
      bucket: {{ $objStoreConfig.bucket }}
      region: {{ $objStoreConfig.region }}
      access_key: {{ $objStoreConfig.access_key }}
      secret_key: {{ $objStoreConfig.secret_key }}
      {{- end }}
      path_prefix: {{ $objStoreConfig.path_prefix | quote }}
      path_certs: {{ $objStoreConfig.path_certs | quote }}
      path_crl: {{ $objStoreConfig.path_crl | quote }}
      path_locks: {{ $objStoreConfig.path_locks | quote }}
      path_states: {{ $objStoreConfig.path_states | quote }}

    {{ with .Values.config.idp -}}
    idp: {{ . | toYaml | nindent 6 }}
    {{- end }}

    {{ with .Values.config.pki -}}
    pki: {{ . | toYaml | nindent 6 }}
    {{- end }}

    {{ with .Values.config.openvpn -}}
    openvpn: {{ . | toYaml | nindent 6 }}
    {{- end }}

  vpn.yml: |-
    {{ with .Values.tunnels -}}
    {{ . | toYaml | nindent 4 }}
    {{- end }}
